[package]
name = "opsc_colab_hub"
version = "0.1.0"
[dependencies]
iron = "*"
router = "0.0.10"
staticfile = "*"
rustc-serialize = "0.3"
[dependencies.mount]

git = "https://github.com/iron/mount.git"
